apiVersion: "v1"
kind: "Template"
metadata:
  name: logging-elasticsearch-template-maker
  annotations:
    description: "Template to create template for deploying ElasticSearch"
    tags: "infrastructure"
objects:
- apiVersion: "v1"
  kind: "Template"
  metadata:
    name: logging-${ES_CLUSTER_NAME}-template
    annotations:
      description: "Template for deploying ElasticSearch with proxy/plugin for storing and retrieving aggregated cluster logs."
      tags: "infrastructure"
    labels:
      logging-infra: elasticsearch
  labels:
    logging-infra: elasticsearch
    provider: openshift
    component: ${ES_CLUSTER_NAME}
  objects:
  -
    apiVersion: "v1"
    kind: "DeploymentConfig"
    metadata:
      name: ${ES_DEPLOYMENT_NAME}
    spec:
      replicas: 1
      selector:
        provider: "openshift"
        component: ${ES_CLUSTER_NAME}
        deployment: ${ES_DEPLOYMENT_NAME}
      triggers:
      - type: ConfigChange
      - type: ImageChange
        imageChangeParams:
          automatic: true
          containerNames:
          - elasticsearch
          from:
            kind: ImageStreamTag
            name: logging-elasticsearch:latest
      strategy:
        resources: {}
        rollingParams:
          intervalSeconds: 1
          timeoutSeconds: 600
          updatePeriodSeconds: 1
        type: Rolling
      template:
        metadata:
          labels:
            provider: "openshift"
            component: ${ES_CLUSTER_NAME}
            deployment: ${ES_DEPLOYMENT_NAME}
        spec:
          serviceAccountName: aggregated-logging
          containers:
            -
              name: "elasticsearch"
              image: logging-elasticsearch
              imagePullPolicy: Always
              ports:
              -
                containerPort: 9200
                name: "restapi"
              -
                containerPort: 9300
                name: "cluster"
              env:
              -
                name: "KUBERNETES_TRUST_CERT"
                value: "true"
              -
                name: "SERVICE_DNS"
                value: "logging-${ES_CLUSTER_NAME}-cluster"
              -
                name: "CLUSTER_NAME"
                value: "logging-${ES_CLUSTER_NAME}"
              volumeMounts:
                - name: elasticsearch
                  mountPath: /etc/elasticsearch/keys
                  readOnly: true
                - name: elasticsearch-storage
                  mountPath: /elasticsearch/persistent
          volumes:
            - name: elasticsearch
              secret:
                secretName: logging-elasticsearch
            - name: elasticsearch-storage
              emptyDir: {}
  parameters:
  -
    description: 'Use to create multiple deployments in order to "scale"; will share services but must have different names.'
    name: ES_DEPLOYMENT_NAME
    from: 'logging-${ES_CLUSTER_NAME}-[a-z0-9]{8}'
    generate: expression
parameters:
-
  description: 'Vary to create templates for multiple clusters with different identities'
  name: ES_CLUSTER_NAME
  value: 'es'
