apiVersion: "v1"
kind: "Template"
metadata:
  name: logging-images-template-maker
  annotations:
    description: "Template to create template for deploying logging support entities"
    tags: "infrastructure"
objects:
- apiVersion: "v1"
  kind: "Template"
  metadata:
    name: logging-images-template
    annotations:
      description: "Template for deploying logging support entities: imagestreams."
      tags: "infrastructure"
    labels:
      logging-infra: support
  labels:
    logging-infra: support
    provider: openshift
    component: support
  objects:
  -
    apiVersion: v1
    kind: ImageStream
    metadata:
      annotations:
        openshift.io/image.insecureRepository: "true"
      name: logging-auth-proxy
    spec:
      dockerImageRepository: ${IMAGE_PREFIX}logging-auth-proxy:${IMAGE_VERSION}
  -
    apiVersion: v1
    kind: ImageStream
    metadata:
      annotations:
        openshift.io/image.insecureRepository: "true"
      name: logging-elasticsearch
    spec:
      dockerImageRepository: ${IMAGE_PREFIX}logging-elasticsearch:${IMAGE_VERSION}
  -
    apiVersion: v1
    kind: ImageStream
    metadata:
      annotations:
        openshift.io/image.insecureRepository: "true"
      name: logging-fluentd
    spec:
      dockerImageRepository: ${IMAGE_PREFIX}logging-fluentd:${IMAGE_VERSION}
  -
    apiVersion: v1
    kind: ImageStream
    metadata:
      annotations:
        openshift.io/image.insecureRepository: "true"
      name: logging-kibana
    spec:
      dockerImageRepository: ${IMAGE_PREFIX}logging-kibana:${IMAGE_VERSION}
  -
    apiVersion: v1
    kind: ImageStream
    metadata:
      annotations:
        openshift.io/image.insecureRepository: "true"
      name: logging-curator
    spec:
      dockerImageRepository: ${IMAGE_PREFIX}logging-curator:${IMAGE_VERSION}
parameters:
-
  description: 'Specify prefix for logging component images; e.g. for "openshift/origin-logging-deployer:v1.1", set prefix "openshift/origin-"'
  name: IMAGE_PREFIX
  value: "docker.io/openshift/origin-"
-
  description: 'Specify version for logging component images; e.g. for "openshift/origin-logging-deployer:v1.1", set version "v1.1"'
  name: IMAGE_VERSION
  value: "latest"
