apiVersion: "v1"
kind: "Template"
metadata:
  name: logging-deployer-template
  annotations:
    description: "Template for deploying everything needed for aggregated logging. Requires cluster-admin 'logging-deployer' service account and 'logging-deployer' secret."
    tags: "infrastructure"
labels:
  logging-infra: deployer
  provider: openshift
  component: deployer
objects:
-
  apiVersion: v1
  kind: Pod
  metadata:
    generateName: logging-deployer-
  spec:
    containers:
    - image: ${IMAGE_PREFIX}logging-deployment:${IMAGE_VERSION}
      imagePullPolicy: Always
      name: deployer
      volumeMounts:
      - name: secret
        mountPath: /secret
        readOnly: true
      - name: empty
        mountPath: /etc/deploy
      env:
        - name: PROJECT
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: IMAGE_PREFIX
          value: ${IMAGE_PREFIX}
        - name: IMAGE_VERSION
          value: ${IMAGE_VERSION}
        - name: ENABLE_OPS_CLUSTER
          value: ${ENABLE_OPS_CLUSTER}
        - name: ES_VOLUME_CAPACITY
          value: ${ES_VOLUME_CAPACITY}
        - name: KIBANA_HOSTNAME
          value: ${KIBANA_HOSTNAME}
        - name: PUBLIC_MASTER_URL
          value: ${PUBLIC_MASTER_URL}
        - name: MASTER_URL
          value: ${MASTER_URL}
    dnsPolicy: ClusterFirst
    restartPolicy: Never
    serviceAccount: logging-deployer
    volumes:
    - name: empty
      emptyDir: {}
    - name: secret
      secret:
        secretName: logging-deployer
parameters:
-
  description: 'Specify prefix for logging components; e.g. for "openshift/origin-logging-deployer:v1.1", set prefix "openshift/origin-"'
  name: IMAGE_PREFIX
  value: "docker.io/openshift/origin-"
-
  description: 'Specify version for logging components; e.g. for "openshift/origin-logging-deployer:v1.1", set version "v1.1"'
  name: IMAGE_VERSION
  value: "latest"
-
  description: "If true, set up to use a second ES cluster for ops logs."
  name: ENABLE_OPS_CLUSTER
  value: "false"
-
  description: 'Gigabytes of persistent storage required per ElasticSearch instance'
  name: ES_VOLUME_CAPACITY
  required: true
-
  description: "External hostname where clients will reach kibana"
  name: KIBANA_HOSTNAME
  required: true
-
  description: "External URL for the master, for OAuth purposes"
  name: PUBLIC_MASTER_URL
  required: true
-
  description: "Internal URL for the master, for authentication retrieval"
  name: MASTER_URL
  value: "https://kubernetes.default.svc.cluster.local"
