apiVersion: "v1"
kind: "Template"
metadata:
  name: logging-deployer-account-template
  annotations:
    description: "Template for creating the deployer account and roles needed for the aggregated logging deployer. Create as cluster-admin."
    tags: "infrastructure"
objects:
- apiVersion: v1
  kind: ServiceAccount
  name: logging-deployer
  metadata:
    name: logging-deployer
    labels:
      logging-infra: deployer
      provider: openshift
      component: deployer
  secrets:
- apiVersion: v1
  kind: ClusterRole
  metadata:
    name: oauth-editor
  rules:
  - resources:
    - oauthclients
    verbs:
    - create
    - delete
- apiVersion: v1
  kind: ClusterRole
  metadata:
    name: daemonset-admin
  rules:
  - resources:
    - daemonsets
    apiGroups:
    - extensions
    verbs:
    - create
    - get
    - list
    - watch
    - delete
    - update
